### ISSUE TITLE
Add RBAC policy example

### ISSUE THREAD

**Issue by AndrewDryga** [ultimateboy/slack8s#4]
Never Kubernetes releases enable RBAC by default, which means that this pod won't be able to requests API unless policy is created.

It would be nice to have an example of role and rolebinding.

**Comment by AndrewDryga** [comment]
Example policy that works on our cluster:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: monitoring
  name: slack-events-watcher
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["events"]
  verbs: ["list", "watch", "get"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: monitoring
  name: watch-events
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: slack-events-watcher
  apiGroup: rbac.authorization.k8s.io
```
